apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: deploy-to-prod
spec:
  application: simple-python
  displayName: deploy-to-prod
  target: rh-ee-sconroy-tenant
